# Anker SOLIX PS100 Solar Panel System Configuration
# Updated: June 10, 2025

panel_specs:
  model: "Anker SOLIX PS100"
  manufacturer: "Anker"
  cell_type: "Monocrystalline"
  efficiency: 23  # percent
  
  electrical:
    peak_power: 100  # watts
    rated_voltage_vmp: 26.5  # volts (operating voltage)
    open_circuit_voltage_voc: 24.5  # volts
    rated_current_imp: 3.77  # amps (operating current)
    short_circuit_current_isc: 4.1  # amps
    
  system_limits:
    max_current_fused: 10.0  # amps (your 10A inline fuse)
    max_voltage_operating: 30.0  # volts (with safety margin)
    max_power_expected: 120.0  # watts (with margin)
    
  physical:
    dimensions_folded: [557, 608, 32]  # mm [length, width, thickness]
    dimensions_unfolded: [1120, 608, 28]  # mm
    weight: 4.6  # kg
    waterproof_rating: "IP67"
    
  connectors:
    output: "MC4 solar-standard"
    charging_cable: "XT60→DC7909"
    
  warranty:
    standard: 18  # months
    eu: 24  # months

# INA228 Sensor Configuration for PS100
sensor_config:
  model: "INA228"
  shunt_resistance: 0.015  # ohms (15mΩ integrated shunt)
  max_current: 10.0  # amps (matches fuse rating)
  max_voltage: 30.0  # volts
  resolution:
    voltage: 0.0001  # 100µV per LSB
    current: 0.001   # 1mA per LSB
    power: 0.001     # 1mW per LSB
    
# Monitoring Configuration
monitoring:
  sample_rate: 2  # seconds between readings
  data_retention: 365  # days
  aggregation_intervals: [60, 300, 3600]  # seconds: 1min, 5min, 1hour
  
  alert_thresholds:
    min_voltage: 18.0  # volts (below useful operating range)
    max_voltage: 25.0  # volts (approaching Voc)
    max_current: 9.5   # amps (below fuse rating with margin)
    min_power_efficiency: 0.75  # 75% of rated power under good conditions
    max_temperature: 70.0  # celsius (sensor protection)
    
  performance_expectations:
    excellent_conditions:  # Full sun, optimal temperature
      voltage_range: [25.0, 26.5]
      current_range: [3.5, 3.8]
      power_range: [90, 100]
    good_conditions:  # Partial sun
      voltage_range: [22.0, 26.0]
      current_range: [2.0, 3.5]
      power_range: [50, 90]
    poor_conditions:  # Cloudy/shade
      voltage_range: [18.0, 24.0]
      current_range: [0.5, 2.0]
      power_range: [10, 50]

# Multi-Panel Support
system:
  max_panels: 8  # Support up to 8 panels
  i2c_addresses: [0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47]
  total_system_power: 800  # watts (8 × 100W)
  panel_naming_convention: "PS100_{location}_{number}"
